"""
Steps AI Mock Interview Data Models.

This module defines Pydantic schemas and Enums for managing mock interview
sessions, including start requests, message turns, submissions, and status checks.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum

class InterviewMode(str, Enum):
    HR = "HR"
    TECHNICAL = "Technical"
    BEHAVIORAL = "Behavioral"

class DifficultyLevel(str, Enum):
    JUNIOR = "Junior"
    MID = "Mid"
    SENIOR = "Senior"

class Message(BaseModel):
    """
    Represents a single message turn in the interview conversation history.
    """
    role: str = Field(..., description="The speaker role: 'system', 'user' (candidate), or 'assistant' (AI recruiter).")
    content: str = Field(..., description="The textual message content.")

class StartInterviewRequest(BaseModel):
    """
    Payload required to initiate a new mock interview session using an uploaded resume.
    """
    resume_session_id: str = Field(
        ..., 
        description="The Resume parsing Session ID acquired during Phase 2 upload."
    )
    interview_mode: InterviewMode = Field(
        default=InterviewMode.TECHNICAL,
        description="Core focus of the interview: HR, Technical, or Behavioral."
    )
    difficulty_level: Optional[DifficultyLevel] = Field(
        default=None,
        description="Seniority tier. If not specified, auto-detected from the resume profile."
    )
    total_questions: int = Field(
        default=5, 
        ge=3, 
        le=10, 
        description="Total number of conversational questions planned for this session."
    )

class StartInterviewResponse(BaseModel):
    """
    Response returned after successfully launching an interview session.
    """
    interview_session_id: str = Field(..., description="Unique UUID assigned to this active interview session.")
    resume_session_id: str = Field(..., description="Binding resume session ID.")
    first_question: str = Field(..., description="The opening introduction and initial question generated by Llama.")
    interview_mode: InterviewMode = Field(..., description="Active interview focus mode.")
    difficulty_level: DifficultyLevel = Field(..., description="Target seniority tier of the interview.")
    total_questions: int = Field(..., description="Configured question count limit.")

class SubmitAnswerRequest(BaseModel):
    """
    Payload containing the candidate's response to the active question.
    """
    session_id: str = Field(..., description="Unique UUID identifying the ongoing interview session.")
    answer: str = Field(..., description="Candidate's text response to the current question.")

class SubmitAnswerResponse(BaseModel):
    """
    Response returned after submitting an answer (non-streaming legacy, or schema for API docs).
    """
    next_question: str = Field(..., description="The follow-up response or the next question. Concluding remark if completed.")
    current_question_index: int = Field(..., description="The index of the question that was just answered (1-indexed).")
    total_questions: int = Field(..., description="Total questions allocated for the session.")
    completed: bool = Field(..., description="True if this was the final turn and the interview has closed.")

class SessionStatusResponse(BaseModel):
    session_id: str
    question_count: int
    total_questions: int
    current_difficulty: str
    interview_mode: str
    elapsed_seconds: int
    is_complete: bool
